import { z } from 'zod';
import {
  toErrorResponse,
  toJsonResponse,
  type ToolContext,
  type ToolDefinition,
  type ToolResponse,
} from '../types.js';

// ---------- create_group ----------

const CreateGroupSchema = z
  .object({
    course_id: z.number().int().positive(),
    name: z.string().min(1).max(254),
    description: z.string().default(''),
    idnumber: z
      .string()
      .default('')
      .describe('Optional stable idnumber. Empty = auto-generated by Moodle.'),
  })
  .strict();

export type CreateGroupInput = z.infer<typeof CreateGroupSchema>;

export function buildCreateGroupTool(): ToolDefinition<CreateGroupInput> {
  return {
    name: 'create_group',
    description:
      'Create a group inside a course. Use assign_to_group to populate it after.',
    inputSchema: CreateGroupSchema,
    handler: (args, ctx) => createGroup(args, ctx),
  };
}

export const createGroupTool = buildCreateGroupTool();

async function createGroup(args: CreateGroupInput, ctx: ToolContext): Promise<ToolResponse> {
  try {
    const created = (await ctx.client.call('core_group_create_groups', {
      groups: [
        {
          courseid: args.course_id,
          name: args.name,
          description: args.description,
          descriptionformat: 1,
          ...(args.idnumber !== '' && { idnumber: args.idnumber }),
        },
      ],
    })) as Array<{ id: number; name: string; idnumber?: string }> | undefined;

    if (!Array.isArray(created) || created.length === 0) {
      throw new Error('core_group_create_groups returned no group');
    }

    const g = created[0]!;
    return toJsonResponse({
      group_id: g.id,
      name: g.name,
      idnumber: g.idnumber ?? null,
      course_id: args.course_id,
    });
  } catch (e) {
    ctx.logger.warn('create_group.failed', {
      course_id: args.course_id,
      error: (e as Error).message,
    });
    return toErrorResponse(e);
  }
}

// ---------- assign_to_group ----------

const AssignGroupSchema = z
  .object({
    group_id: z.number().int().positive(),
    user_ids: z.array(z.number().int().positive()).min(1),
  })
  .strict();

export type AssignToGroupInput = z.infer<typeof AssignGroupSchema>;

export function buildAssignToGroupTool(): ToolDefinition<AssignToGroupInput> {
  return {
    name: 'assign_to_group',
    description: 'Add one or more users to a group by group_id.',
    inputSchema: AssignGroupSchema,
    handler: (args, ctx) => assign(args, ctx),
  };
}

export const assignToGroupTool = buildAssignToGroupTool();

async function assign(args: AssignToGroupInput, ctx: ToolContext): Promise<ToolResponse> {
  try {
    await ctx.client.call('core_group_add_group_members', {
      members: args.user_ids.map((userid) => ({ groupid: args.group_id, userid })),
    });
    return toJsonResponse({
      group_id: args.group_id,
      added: args.user_ids.length,
      user_ids: args.user_ids,
    });
  } catch (e) {
    ctx.logger.warn('assign_to_group.failed', {
      group_id: args.group_id,
      count: args.user_ids.length,
      error: (e as Error).message,
    });
    return toErrorResponse(e);
  }
}
